// <auto-generated />
using System;
using ATSProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ATSProject.Migrations
{
    [DbContext(typeof(ATSContext))]
    [Migration("20250917153554_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ATSProject.Models.Candidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CvFilePath")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("DateApplied")
                        .HasColumnType("datetime2");

                    b.Property<string>("Education")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Experience")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GmailMessageId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RoleApplied")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Skills")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UniqueId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Candidates");
                });

            modelBuilder.Entity("ATSProject.Models.CandidateApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<string>("ResumePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("CandidateApplications");
                });

            modelBuilder.Entity("ATSProject.Models.CandidateField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FieldName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("CandidateFields");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FieldName = "Full Name",
                            FieldType = "Text",
                            IsMandatory = true
                        },
                        new
                        {
                            Id = 2,
                            FieldName = "Gender",
                            FieldType = "Text",
                            IsMandatory = true
                        },
                        new
                        {
                            Id = 3,
                            FieldName = "Date of Birth",
                            FieldType = "Date",
                            IsMandatory = true
                        },
                        new
                        {
                            Id = 4,
                            FieldName = "Nationality",
                            FieldType = "Text",
                            IsMandatory = true
                        },
                        new
                        {
                            Id = 5,
                            FieldName = "CNIC / Passport No.",
                            FieldType = "Text",
                            IsMandatory = true
                        },
                        new
                        {
                            Id = 6,
                            FieldName = "Marital Status",
                            FieldType = "Text",
                            IsMandatory = false
                        },
                        new
                        {
                            Id = 7,
                            FieldName = "Religion",
                            FieldType = "Text",
                            IsMandatory = false
                        },
                        new
                        {
                            Id = 8,
                            FieldName = "Contact Number(s)",
                            FieldType = "Text",
                            IsMandatory = true
                        },
                        new
                        {
                            Id = 9,
                            FieldName = "Email Address",
                            FieldType = "Email",
                            IsMandatory = true
                        },
                        new
                        {
                            Id = 10,
                            FieldName = "Current Address",
                            FieldType = "Text",
                            IsMandatory = true
                        },
                        new
                        {
                            Id = 11,
                            FieldName = "Permanent Address",
                            FieldType = "Text",
                            IsMandatory = true
                        },
                        new
                        {
                            Id = 12,
                            FieldName = "LinkedIn Profile URL",
                            FieldType = "Text",
                            IsMandatory = false
                        },
                        new
                        {
                            Id = 13,
                            FieldName = "Other Social Media / Portfolio Links",
                            FieldType = "Text",
                            IsMandatory = false
                        },
                        new
                        {
                            Id = 14,
                            FieldName = "Professional Website / Blog",
                            FieldType = "Text",
                            IsMandatory = false
                        },
                        new
                        {
                            Id = 15,
                            FieldName = "Photograph",
                            FieldType = "File",
                            IsMandatory = false
                        },
                        new
                        {
                            Id = 16,
                            FieldName = "Job Titles Applying For",
                            FieldType = "Text",
                            IsMandatory = true
                        },
                        new
                        {
                            Id = 17,
                            FieldName = "Job Requisition ID",
                            FieldType = "Text",
                            IsMandatory = false
                        },
                        new
                        {
                            Id = 18,
                            FieldName = "Location(s)",
                            FieldType = "Text",
                            IsMandatory = true
                        },
                        new
                        {
                            Id = 19,
                            FieldName = "Open to Relocation?",
                            FieldType = "Text",
                            IsMandatory = false
                        },
                        new
                        {
                            Id = 20,
                            FieldName = "Relocation Preference",
                            FieldType = "Text",
                            IsMandatory = false
                        },
                        new
                        {
                            Id = 21,
                            FieldName = "Willing to Travel?",
                            FieldType = "Text",
                            IsMandatory = false
                        },
                        new
                        {
                            Id = 22,
                            FieldName = "Desired Employment Type",
                            FieldType = "Text",
                            IsMandatory = true
                        },
                        new
                        {
                            Id = 23,
                            FieldName = "Remote/Hybrid/On-site Preference",
                            FieldType = "Text",
                            IsMandatory = false
                        },
                        new
                        {
                            Id = 24,
                            FieldName = "Earliest Possible Joining Date",
                            FieldType = "Date",
                            IsMandatory = true
                        },
                        new
                        {
                            Id = 25,
                            FieldName = "Notice Period",
                            FieldType = "Text",
                            IsMandatory = false
                        },
                        new
                        {
                            Id = 26,
                            FieldName = "Highest Qualification Obtained",
                            FieldType = "Text",
                            IsMandatory = true
                        },
                        new
                        {
                            Id = 27,
                            FieldName = "Education Level(s)",
                            FieldType = "Text",
                            IsMandatory = false
                        },
                        new
                        {
                            Id = 28,
                            FieldName = "Institute / University Name",
                            FieldType = "Text",
                            IsMandatory = true
                        },
                        new
                        {
                            Id = 29,
                            FieldName = "Country of Education",
                            FieldType = "Text",
                            IsMandatory = false
                        },
                        new
                        {
                            Id = 30,
                            FieldName = "Major / Field of Study",
                            FieldType = "Text",
                            IsMandatory = true
                        },
                        new
                        {
                            Id = 31,
                            FieldName = "Graduation Year(s)",
                            FieldType = "Text",
                            IsMandatory = false
                        },
                        new
                        {
                            Id = 32,
                            FieldName = "GPA / Percentage / Division",
                            FieldType = "Text",
                            IsMandatory = false
                        },
                        new
                        {
                            Id = 33,
                            FieldName = "Certifications",
                            FieldType = "Text",
                            IsMandatory = false
                        },
                        new
                        {
                            Id = 34,
                            FieldName = "Ongoing Courses / Learning Programs",
                            FieldType = "Text",
                            IsMandatory = false
                        },
                        new
                        {
                            Id = 35,
                            FieldName = "Employer Name",
                            FieldType = "Text",
                            IsMandatory = true
                        },
                        new
                        {
                            Id = 36,
                            FieldName = "Industry",
                            FieldType = "Text",
                            IsMandatory = true
                        },
                        new
                        {
                            Id = 37,
                            FieldName = "Job Title",
                            FieldType = "Text",
                            IsMandatory = true
                        },
                        new
                        {
                            Id = 38,
                            FieldName = "Start Date – End Date",
                            FieldType = "Text",
                            IsMandatory = true
                        },
                        new
                        {
                            Id = 39,
                            FieldName = "Employment Type",
                            FieldType = "Text",
                            IsMandatory = true
                        },
                        new
                        {
                            Id = 40,
                            FieldName = "Job Responsibilities",
                            FieldType = "Text",
                            IsMandatory = false
                        },
                        new
                        {
                            Id = 41,
                            FieldName = "Key Achievements",
                            FieldType = "Text",
                            IsMandatory = false
                        },
                        new
                        {
                            Id = 42,
                            FieldName = "Reason for Leaving",
                            FieldType = "Text",
                            IsMandatory = false
                        },
                        new
                        {
                            Id = 43,
                            FieldName = "Last Drawn Salary & Benefits",
                            FieldType = "Text",
                            IsMandatory = false
                        },
                        new
                        {
                            Id = 44,
                            FieldName = "Reporting Manager’s Name & Contact",
                            FieldType = "Text",
                            IsMandatory = false
                        },
                        new
                        {
                            Id = 45,
                            FieldName = "International Work Experience?",
                            FieldType = "Text",
                            IsMandatory = false
                        },
                        new
                        {
                            Id = 46,
                            FieldName = "Startup vs Corporate Experience",
                            FieldType = "Text",
                            IsMandatory = false
                        },
                        new
                        {
                            Id = 47,
                            FieldName = "Freelance / Contract Experience",
                            FieldType = "Text",
                            IsMandatory = false
                        },
                        new
                        {
                            Id = 48,
                            FieldName = "Technical Skills",
                            FieldType = "Text",
                            IsMandatory = true
                        },
                        new
                        {
                            Id = 49,
                            FieldName = "Soft Skills",
                            FieldType = "Text",
                            IsMandatory = false
                        },
                        new
                        {
                            Id = 50,
                            FieldName = "Tools/Software Knowledge",
                            FieldType = "Text",
                            IsMandatory = false
                        },
                        new
                        {
                            Id = 51,
                            FieldName = "Programming Languages / Frameworks",
                            FieldType = "Text",
                            IsMandatory = false
                        },
                        new
                        {
                            Id = 52,
                            FieldName = "Certifications (Professional / IT / HR / Finance / Language)",
                            FieldType = "Text",
                            IsMandatory = false
                        },
                        new
                        {
                            Id = 53,
                            FieldName = "Language Proficiency",
                            FieldType = "Text",
                            IsMandatory = false
                        },
                        new
                        {
                            Id = 54,
                            FieldName = "Current Industry",
                            FieldType = "Text",
                            IsMandatory = true
                        },
                        new
                        {
                            Id = 55,
                            FieldName = "Previous Industry Experience",
                            FieldType = "Text",
                            IsMandatory = false
                        },
                        new
                        {
                            Id = 56,
                            FieldName = "Preferred Industry",
                            FieldType = "Text",
                            IsMandatory = false
                        },
                        new
                        {
                            Id = 57,
                            FieldName = "Sector Exposure",
                            FieldType = "Text",
                            IsMandatory = false
                        },
                        new
                        {
                            Id = 58,
                            FieldName = "Functional Expertise",
                            FieldType = "Text",
                            IsMandatory = false
                        },
                        new
                        {
                            Id = 59,
                            FieldName = "Sub-Domain Expertise",
                            FieldType = "Text",
                            IsMandatory = false
                        },
                        new
                        {
                            Id = 60,
                            FieldName = "Management Level",
                            FieldType = "Text",
                            IsMandatory = true
                        },
                        new
                        {
                            Id = 61,
                            FieldName = "Preferred Job Function",
                            FieldType = "Text",
                            IsMandatory = false
                        },
                        new
                        {
                            Id = 62,
                            FieldName = "Preferred Work Environment",
                            FieldType = "Text",
                            IsMandatory = false
                        },
                        new
                        {
                            Id = 63,
                            FieldName = "Preferred Industry Sector(s)",
                            FieldType = "Text",
                            IsMandatory = false
                        },
                        new
                        {
                            Id = 64,
                            FieldName = "Preferred Currency for Salary",
                            FieldType = "Text",
                            IsMandatory = false
                        },
                        new
                        {
                            Id = 65,
                            FieldName = "Work Authorization Status",
                            FieldType = "Text",
                            IsMandatory = false
                        },
                        new
                        {
                            Id = 66,
                            FieldName = "Visa / Work Permit Status",
                            FieldType = "Text",
                            IsMandatory = false
                        },
                        new
                        {
                            Id = 67,
                            FieldName = "Convicted of a crime?",
                            FieldType = "Text",
                            IsMandatory = false
                        },
                        new
                        {
                            Id = 68,
                            FieldName = "Legal restrictions for employment?",
                            FieldType = "Text",
                            IsMandatory = false
                        },
                        new
                        {
                            Id = 69,
                            FieldName = "Contractual obligations / non-compete clauses?",
                            FieldType = "Text",
                            IsMandatory = false
                        },
                        new
                        {
                            Id = 70,
                            FieldName = "Medically fit for applied role?",
                            FieldType = "Text",
                            IsMandatory = false
                        },
                        new
                        {
                            Id = 71,
                            FieldName = "Tax Registration Number",
                            FieldType = "Text",
                            IsMandatory = false
                        },
                        new
                        {
                            Id = 72,
                            FieldName = "Willingness to undergo background check?",
                            FieldType = "Text",
                            IsMandatory = false
                        },
                        new
                        {
                            Id = 73,
                            FieldName = "Willingness to undergo medical examination?",
                            FieldType = "Text",
                            IsMandatory = false
                        },
                        new
                        {
                            Id = 74,
                            FieldName = "Reference 1: Name",
                            FieldType = "Text",
                            IsMandatory = false
                        },
                        new
                        {
                            Id = 75,
                            FieldName = "Reference 1: CNIC #",
                            FieldType = "Text",
                            IsMandatory = false
                        },
                        new
                        {
                            Id = 76,
                            FieldName = "Reference 1: Designation",
                            FieldType = "Text",
                            IsMandatory = false
                        },
                        new
                        {
                            Id = 77,
                            FieldName = "Reference 1: Organization",
                            FieldType = "Text",
                            IsMandatory = false
                        },
                        new
                        {
                            Id = 78,
                            FieldName = "Reference 1: Relationship",
                            FieldType = "Text",
                            IsMandatory = false
                        },
                        new
                        {
                            Id = 79,
                            FieldName = "Reference 1: Contact Info",
                            FieldType = "Text",
                            IsMandatory = false
                        },
                        new
                        {
                            Id = 80,
                            FieldName = "Reference 2: Name",
                            FieldType = "Text",
                            IsMandatory = false
                        },
                        new
                        {
                            Id = 81,
                            FieldName = "Reference 2: CNIC #",
                            FieldType = "Text",
                            IsMandatory = false
                        },
                        new
                        {
                            Id = 82,
                            FieldName = "Reference 2: Designation",
                            FieldType = "Text",
                            IsMandatory = false
                        },
                        new
                        {
                            Id = 83,
                            FieldName = "Reference 2: Organization",
                            FieldType = "Text",
                            IsMandatory = false
                        },
                        new
                        {
                            Id = 84,
                            FieldName = "Reference 2: Relationship",
                            FieldType = "Text",
                            IsMandatory = false
                        },
                        new
                        {
                            Id = 85,
                            FieldName = "Reference 2: Contact Info",
                            FieldType = "Text",
                            IsMandatory = false
                        },
                        new
                        {
                            Id = 86,
                            FieldName = "How did you hear about this job?",
                            FieldType = "Text",
                            IsMandatory = false
                        },
                        new
                        {
                            Id = 87,
                            FieldName = "Referral Name (if any)",
                            FieldType = "Text",
                            IsMandatory = false
                        },
                        new
                        {
                            Id = 88,
                            FieldName = "Availability for interviews",
                            FieldType = "Text",
                            IsMandatory = false
                        },
                        new
                        {
                            Id = 89,
                            FieldName = "Upload Resume / CV",
                            FieldType = "File",
                            IsMandatory = true
                        },
                        new
                        {
                            Id = 90,
                            FieldName = "Upload Cover Letter",
                            FieldType = "File",
                            IsMandatory = false
                        },
                        new
                        {
                            Id = 91,
                            FieldName = "Upload Portfolio",
                            FieldType = "File",
                            IsMandatory = false
                        },
                        new
                        {
                            Id = 92,
                            FieldName = "Upload Certificates / Transcripts",
                            FieldType = "File",
                            IsMandatory = false
                        },
                        new
                        {
                            Id = 93,
                            FieldName = "Declaration Checkbox",
                            FieldType = "Text",
                            IsMandatory = true
                        },
                        new
                        {
                            Id = 94,
                            FieldName = "Digital Signature / Typed Name",
                            FieldType = "Text",
                            IsMandatory = true
                        },
                        new
                        {
                            Id = 95,
                            FieldName = "Date/Time of Submission",
                            FieldType = "Date",
                            IsMandatory = true
                        });
                });

            modelBuilder.Entity("ATSProject.Models.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("ATSProject.Models.JobRequiredField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidateFieldId")
                        .HasColumnType("int");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CandidateFieldId");

                    b.HasIndex("JobId");

                    b.ToTable("JobRequiredFields");
                });

            modelBuilder.Entity("CandidateResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidateApplicationId")
                        .HasColumnType("int");

                    b.Property<int>("CandidateFieldId")
                        .HasColumnType("int");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<string>("Response")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CandidateApplicationId");

                    b.HasIndex("CandidateFieldId");

                    b.HasIndex("JobId");

                    b.ToTable("CandidateResponses");
                });

            modelBuilder.Entity("ATSProject.Models.CandidateApplication", b =>
                {
                    b.HasOne("ATSProject.Models.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("ATSProject.Models.JobRequiredField", b =>
                {
                    b.HasOne("ATSProject.Models.CandidateField", "CandidateField")
                        .WithMany()
                        .HasForeignKey("CandidateFieldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ATSProject.Models.Job", "Job")
                        .WithMany("JobRequiredFields")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CandidateField");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("CandidateResponse", b =>
                {
                    b.HasOne("ATSProject.Models.CandidateApplication", "Application")
                        .WithMany("CandidateResponses")
                        .HasForeignKey("CandidateApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ATSProject.Models.CandidateField", "CandidateField")
                        .WithMany()
                        .HasForeignKey("CandidateFieldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ATSProject.Models.Job", "Job")
                        .WithMany("CandidateResponses")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("CandidateField");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("ATSProject.Models.CandidateApplication", b =>
                {
                    b.Navigation("CandidateResponses");
                });

            modelBuilder.Entity("ATSProject.Models.Job", b =>
                {
                    b.Navigation("CandidateResponses");

                    b.Navigation("JobRequiredFields");
                });
#pragma warning restore 612, 618
        }
    }
}
